name: po_frontend
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_gradient_text: 1.2.4
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  shared_preferences: ^2.0.15
  provider: ^6.0.4
  envify:
    git:
      url: https://github.com/ThexXTURBOXx/envify.git
      ref: dev
      path: envify
  dart_jsonwebtoken: ^2.4.2
  enum_to_string: ^2.0.1
  url_launcher: ^6.1.7
  auto_size_text: ^3.0.0
  flutter_datetime_picker: ^1.5.1
  syncfusion_flutter_gauges: ^20.3.60
  font_awesome_flutter: ^10.3.0
  go_router: ^5.2.2
  flutter_switch: ^0.3.2
  file_picker: ^5.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  json_serializable: ^6.5.3
  flutter_lints: ^2.0.0
  envify_generator:
    git:
      url: https://github.com/ThexXTURBOXx/envify.git
      ref: dev
      path: envify_generator

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - Afbeeldingen/Mountains.png
    - Afbeeldingen/parking.png
